blank_issues_enabled: true
contact_links:
  - name: Actix Discord
    url: https://discord.gg/NWpN5mmg3x
    about: Actix developer discussion and community chat
  - name: GitHub Discussions
    url: https://github.com/actix/actix-web/discussions
    about: Actix Web Q&A
